### PR TITLE
update the doc for `deform_conv2d`

### PR DESCRIPTION
**Pull request by lartpang**
Update the previous complex example to highlight the relationship between `offset_groups` and the channels of the input features.

### CODE REVIEW

**Comment by lartpang** [comment]
@voldemortX

**Comment by voldemortX** [comment]
@lartpang Thanks again! But there seems to be some merge conflicts?

**Comment by lartpang** [comment]
@voldemortX 

Yes. Because this update overwrites the previous example. This may not be compatible. Maybe you can try to modify it? 😅 

And you are also welcome to provide some suggestions for this example, or even enhance it. There might be something I've overlooked.

**Comment by voldemortX** [comment]
> @voldemortX 
> 
> Yes. Because this update overwrites the previous example. This may not be compatible. Maybe you can try to modify it? 😅 
> 
> And you are also welcome to provide some suggestions for this example, or even enhance it. There might be something I've overlooked.

Great! I will look into it.

**Pull request merged**
